# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813c4816c91810d035c441d6f8ae6edcc95785a70ba88237040d23881aef4d3279845a3bb38d9b1b7ef6c8b034241a8c28dd42f976e7d734268fa706a301fa40

test:
  secret_key_base: 56738e9c63f083f9a06f615f710b0fce63763f2984cc5faaf01f45139b358de5816363c8045c067c987bfc15b6801478e5ef94f248eff4b8e0bcded2f7b13a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
